
server:
  servlet:
    context-path: /inventory

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomerce
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
