
server:
  port: 8081
  servlet:
    context-path: /inventory-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomerce?reWriteBatchedInserts=true
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: inventory_service
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: inventory_service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 3 # default is 5
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      groupId: test-consumer
    properties:
      specific:
        avro:
          reader: true
      schema:
        registry:
          url: http://localhost:8087

logging:
  level:
    org.hibernate:
      engine.jdbc.batch.internal.BatchingBatch: DEBUG
